version: '3'

networks:
  web:
    external: true
  discord-email-bridge:
    external: false

services:
  bridge:
    build: .
    env_file: .env
    labels:
      # https://docs.traefik.io/basics/#examples
      - traefik.backend=discord-email-bridge
      - traefik.frontend.rule=Host:outdatedversion.com;PathPrefix:/discord-email-bridge;PathPrefixStrip:/discord-email-bridge
      - traefik.docker.network=web
      - traefik.port=2000 # port exposed during image build
    networks:
      - discord-email-bridge
      - web
