version: '3'

networks:
  web:
    external: true
  discord-email-bridge:
    external: false

services:
  bridge:
    image: outdatedversion/discord-email-bridge
    environment:
      - BRIDGE_DISCORD_TOKEN:
      - BRIDGE_DISCORD_CHANNEL_ID:
    labels:
      # https://docs.traefik.io/basics/#examples
      - traefik.backend=discord-email-bridge
      - traefik.frontend.rule=Host:outdatedversion.com;Path:/
      - traefik.docker.network=web
      - traefik.port=2000 # port exposed during image build
    networks:
      - discord-email-bridge
      - web
